---
- name: Check ansible version
  import_playbook: ansible_version.yml

# These are inventory compatibility tasks with two purposes:
# - to ensure we keep compatibility with old style group names
# - to reduce inventory boilerplate (defining parent groups / empty groups)

- name: Add kube-master nodes to kube_control_plane
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to kube_control_plane group
      add_host:
        name: "{{ item }}"
        groups: 'kube_control_plane'
      with_items: "{{ groups['kube-master'] | default([]) }}"

- name: Add kube-node nodes to kube_node
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to kube_node group
      add_host:
        name: "{{ item }}"
        groups: 'kube_node'
      with_items: "{{ groups['kube-node'] | default([]) }}"

- name: Add calico-rr nodes to calico_rr
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to calico_rr group
      add_host:
        name: "{{ item }}"
        groups: 'calico_rr'
      with_items: "{{ groups['calico-rr'] | default([]) }}"

- name: Define k8s_cluster group
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to k8s_cluster group
      add_host:
        name: "{{ item }}"
        groups: 'k8s_cluster'
      with_items: "{{ (groups['kube_node'] | default([])) | union(groups['kube_control_plane'] | default([])) | union(groups['calico_rr'] | default([])) }}"

- name: Add no-floating nodes to no_floating
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to no_floating group
      add_host:
        name: "{{ item }}"
        groups: 'no_floating'
      with_items: "{{ groups['no-floating'] | default([]) }}"

- name: Install bastion ssh config
  hosts: bastion[0]
  gather_facts: false
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"] }
